USE QLTIKIMINI
GO

/*Đăng ký - NBH*/
IF OBJECT_ID('CREATE_ACCOUNT_NBH','P') IS NOT NULL
	DROP PROC CREATE_ACCOUNT_NBH
GO
CREATE PROCEDURE CREATE_ACCOUNT_NBH 
@TENNBH NVARCHAR(50), 
@USERNAMENBH CHAR(20), 
@PASSNBH CHAR(20),
@VAT CHAR(15),
@SDTNBH CHAR(11),
@EMAILNBH CHAR(30),
@MDK_KINHDOANH CHAR(15),
@TENCUAHANG NVARCHAR(50),
@DCHICUAHANG NVARCHAR(100),
@MA_DANHMUCNGANH CHAR(10),
@MA_MHVH CHAR(10)
AS
BEGIN
		DECLARE @ID_NBH INT;
		DECLARE @COUNT INT = (SELECT COUNT(ID_KH) FROM KHACHHANG)
		DECLARE @ROWOFNBH INT =  (SELECT COUNT(ID_NBH) FROM NHABANHANG)
		WHILE(@COUNT > 0)
		BEGIN
			IF(EXISTS (SELECT * FROM KHACHHANG WHERE KHACHHANG.USERNAME_KH  =  @USERNAMENBH))
			BEGIN
				PRINT N'Username của NBH trùng với username của KH. Vui lòng nhập lại'
				RETURN;
			END
			SET @COUNT = @COUNT - 1;
		END
		SET @ID_NBH = @ROWOFNBH + 1;
		INSERT INTO NHABANHANG 
		VALUES(@ID_NBH, @TENNBH, @USERNAMENBH, @PASSNBH, @VAT, @SDTNBH, @EMAILNBH, @MDK_KINHDOANH, @TENCUAHANG, @DCHICUAHANG, @MA_DANHMUCNGANH, @MA_MHVH)
	END
GO 

/*Đăng nhập - NBH*/
IF OBJECT_ID('LOGIN_NBH','P') IS NOT NULL
	DROP PROC LOGIN_NBH
GO
CREATE PROC LOGIN_NBH
@USERNAMENBH CHAR(20), 
@PASSNBH CHAR(20)
AS
BEGIN TRANSACTION
	BEGIN TRY
		IF NOT EXISTS (SELECT * FROM NHABANHANG WHERE NHABANHANG.USERNAMENBH = @USERNAMENBH)
		BEGIN
			PRINT N'Username không tồn tại';
			ROLLBACK TRANSACTION;
			RETURN;
		END
		IF NOT EXISTS (SELECT * FROM NHABANHANG WHERE NHABANHANG.USERNAMENBH = @USERNAMENBH AND NHABANHANG.PASSNBH = @PASSNBH)
		BEGIN
			PRINT N'Sai mật khẩu';
			ROLLBACK TRANSACTION;
			RETURN;
		END
	END TRY
	BEGIN CATCH
		PRINT N'Lỗi đăng nhập'
		ROLLBACK TRANSACTION;
	END CATCH
	PRINT N'Đăng nhập thành công'
COMMIT TRANSACTION
GO

-- Đăng bán sản phẩm SSKU
IF OBJECT_ID('DANGBAN_SANPHAM_SSKU','P') IS NOT NULL
	DROP PROC DANGBAN_SANPHAM_SSKU
GO
CREATE PROC DANGBAN_SANPHAM_SSKU
@ID_NBH INT, 
@TEN_SPHAM NVARCHAR(50),
@MOTACHITIET_SP NVARCHAR(100),
@KHOILUONG SMALLINT,
@GIANIEMYET FLOAT,
@GIAKHUYENMAI FLOAT,
@THOIGIANKM TINYINT,
@SOLUONGTONKHO INT,
@GHICHUSPHAM NVARCHAR(50),
@HANSUDUNGSP SMALLDATETIME,
@NOISX NVARCHAR(50),
@PHITIKITHU INT,
@ID_TH INT,
@ID_DMN INT, 
@ID_THUOCTINHSP INT /*0: COLOR, 1: SIZE, 2: ALL*/,
@TEN_THUOCTINH NVARCHAR(50),
@GIATRITHUOCTINH CHAR(20),
@LOAITHUOCTINH BIT,
@MA_SSKU CHAR(10),
@MINCODE CHAR(15),
@NGAYDANGBANSP SMALLDATETIME
	/*0: COLOR, 1: SIZE */
AS
BEGIN
--Mỗi NBH cần đăng bán ít nhất một sản phẩm SSKU bất kỳ. Nếu không thì không cho phép đăng bán các sản phẩm khác như PSKU hay MSKU nếu vẫn chưa đăng bán ít nhất 1 sản phẩm SSKU nào đó.
--1: PSKU, 2: MSKU, 3: SSKU
	--BEGIN
		IF @KHOILUONG < 0 
		BEGIN
			print N'Khối lượng sản phẩm phải > 0.'
		RETURN;
		END
		IF (@GIAKHUYENMAI > @GIANIEMYET)
		BEGIN
			print N'Giá khuyến mãi phải <= Giá niêm yết.'
		RETURN;
		END
		IF @PHITIKITHU < 0
		BEGIN
			print N'Phí TIKI thu phải > 0.'
		RETURN;
		END

		DECLARE @ID_SP INT 
		SET @ID_SP = (SELECT COUNT(*) FROM dbo.SANPHAM) + 1
		PRINT(@ID_SP)

		INSERT INTO SANPHAM VALUES(@ID_SP, @TEN_SPHAM, @MOTACHITIET_SP,
			@KHOILUONG, @GIANIEMYET, @GIAKHUYENMAI, @THOIGIANKM,
			@SOLUONGTONKHO, @GHICHUSPHAM, @HANSUDUNGSP, 
			@NOISX, @PHITIKITHU, 3, @ID_TH, @ID_DMN)

		INSERT INTO DANGBANSANPHAM VALUES (@ID_NBH, @ID_SP, @NGAYDANGBANSP)

		IF EXISTS (SELECT ID_THUOCTINHSP FROM dbo.THUOCTINHSP WHERE ID_THUOCTINHSP = @ID_THUOCTINHSP)
		BEGIN
		INSERT INTO SSKU VALUES(@ID_SP, @MA_SSKU, @MINCODE)

		INSERT INTO SSKUCOTHUOCTINH VALUES (@ID_THUOCTINHSP, @ID_SP)
		END

END
GO

--Cập nhật giá của những sản phẩm đã đăng bán
IF OBJECT_ID('CAPNHAT_GIABAN','P') IS NOT NULL
	DROP PROC CAPNHAT_GIABAN
GO
CREATE PROC CAPNHAT_GIABAN
@ID_SP INT,
@GIAKHUYENMAI FLOAT
AS
IF @GIAKHUYENMAI > (SELECT GIANIEMYET FROM dbo.SANPHAM WHERE @ID_SP = ID_SP)
BEGIN
	PRINT(N'Giá khuyến mãi phải nhỏ hơn hoặc bằng Giá niêm yết.')
END
ELSE 
UPDATE SANPHAM SET GIAKHUYENMAI = @GIAKHUYENMAI WHERE ID_SP = @ID_SP
GO

-- Lập phiếu gửi hàng
IF OBJECT_ID('LAPPHIEU_GUIHANG','P') IS NOT NULL
	DROP PROC LAPPHIEU_GUIHANG
GO
CREATE PROC LAPPHIEU_GUIHANG 
@MAPO CHAR(10),
@TRANGTHAI TINYINT, --1: Chờ, 0: Hủy
@NGAYPO SMALLDATETIME,
@MINCODEPGH CHAR(15),
@LIENHE NVARCHAR(50),
@NGAYGUIHANGDK SMALLDATETIME,
@GHICHU NVARCHAR(50),
@DIACHIGIAOHANG NVARCHAR(100),
@MA_MHVH CHAR(10), 
@MAKHO CHAR(10),
@ID_NBH INT
AS
DECLARE @ID_PO INT = (SELECT COUNT(*) FROM dbo.PHIEUGUIHANG) + 1
INSERT INTO PHIEUGUIHANG VALUES (@ID_PO, @MAPO, @TRANGTHAI,
		@NGAYPO, @MINCODEPGH, @LIENHE, @NGAYGUIHANGDK,
		N'Nhập kho trực tiếp',@GHICHU, @DIACHIGIAOHANG,
		0, @MA_MHVH, @MAKHO, @ID_NBH)
GO

-- Thêm sản phẩm vào PGH
IF OBJECT_ID('THEMSANPHAM_PGH','P') IS NOT NULL
	DROP PROC THEMSANPHAM_PGH
GO
CREATE PROC THEMSANPHAM_PGH
@ID_PO INT,
@ID_SP INT,
@MABACKORDER CHAR(10),
@SOLUONG SMALLINT,
@DONGIA INT
AS

INSERT INTO CHITIETPHIEUGUIHANG VALUES (@ID_PO, @ID_SP, @MABACKORDER,
											@SOLUONG, @DONGIA)
UPDATE dbo.PHIEUGUIHANG SET TONGTIEN += @DONGIA*@SOLUONG WHERE ID_PO = @ID_PO
GO

/*KỊCH BẢN 2:
- NBH đăng ký tài khoản:
EXEC CREATE_ACCOUNT_NBH N'CHICKIN','user1','123456789','12ABCD','013456789','MSSV@gmail.com','EGHJSKA29','CHICKEN SHOP','NOT NULL',NULL,NULL
GO

- NBH đăng nhập:
EXEC LOGIN_NBH 'user1','123456789'
GO

- NBH đăng bán sản phẩm vào ngày sale 12.12:
+ Đăng bán sản phẩm SSKU:
	EXEC DANGBAN_SANPHAM_SSKU
	@ID_NBH = 1, 
	@TEN_SPHAM = N'SP5',
	@MOTACHITIET_SP = N'NOP',
	@KHOILUONG = 10,
	@GIANIEMYET = 1000,
	@GIAKHUYENMAI = 900,
	@THOIGIANKM = 2,
	@SOLUONGTONKHO = 8,
	@GHICHUSPHAM = N'O',
	@HANSUDUNGSP = '2020-12-22',
	@NOISX = N'TPHCM',
	@PHITIKITHU = 9,
	@ID_TH = NULL,
	@ID_DMN = NULL,
	@ID_THUOCTINHSP = 3, 
	@TEN_THUOCTINH = N'Size',
	@GIATRITHUOCTINH = N'Big',
	@LOAITHUOCTINH = 1,
	@MA_SSKU = 'SSKU05',
	@MINCODE = 'MINCODE05',
	@NGAYDANGBANSP = '2020-11-01'
	GO
	
- NBH cập nhật thông tin về giá khuyến mãi của những sản phẩm:
	/*EXEC dbo.CAPNHAT_GIABAN  @ID_SP = 10, @GIAKHUYENMAI = 210
	GO
	SELECT * FROM dbo.SANPHAM
	INSERT INTO dbo.SANPHAM
	(
		ID_SP,
		TEN_SPHAM,
		MOTACHITIET_SP,
		KHOILUONG,
		GIANIEMYET,
		GIAKHUYENMAI,
		THOIGIANKM,
		SOLUONGTONKHO,
		GHICHUSPHAM,
		HANSUDUNGSP,
		NOISX,
		PHITIKITHU,
		LOAICAUTRUCSP,
		ID_TH,
		ID_DMN
	)
	VALUES
	(   10,                     -- ID_SP - int
		N'SP10',                   -- TEN_SPHAM - nvarchar(50)
		N'NOPE',                   -- MOTACHITIET_SP - nvarchar(100)
		1,                     -- KHOILUONG - smallint
		200.0,                   -- GIANIEMYET - float
		20.0,                   -- GIAKHUYENMAI - float
		1,                     -- THOIGIANKM - tinyint
		2,                     -- SOLUONGTONKHO - int
		N'NOPE',                   -- GHICHUSPHAM - nvarchar(50)
		'2020-12-22 18:15:15', -- HANSUDUNGSP - smalldatetime
		N'TPHCM',                   -- NOISX - nvarchar(50)
		1,                     -- PHITIKITHU - int
		1,                     -- LOAICAUTRUCSP - tinyint
		NULL,                     -- ID_TH - int
		NULL                      -- ID_DMN - int
		)*/

- NBH lập phiếu giao hàng gửi đến kho Tiki:
1) Tạo PGH:
	EXEC dbo.LAPPHIEU_GUIHANG       
							  @MAPO = 'PO20',                             -- char(10)
							  @TRANGTHAI = 0,                         -- tinyint
							  @NGAYPO = '2020-12-22 18:38:54',        -- smalldatetime
							  @MINCODEPGH = 'MINCODE11',                       -- char(15)
							  @LIENHE = N'SB',                          -- nvarchar(50)
							  @NGAYGUIHANGDK = '2020-12-22 18:38:54', -- smalldatetime
							  @GHICHU = N'NOPE',                          -- nvarchar(50)
							  @DIACHIGIAOHANG = N'NOPE',                  -- nvarchar(100)
							  @MA_MHVH = NULL,                          -- char(10)
							  @MAKHO = NULL,                            -- char(10)
							  @ID_NBH = NULL                             -- int
	GO

2) Thêm sản phẩm vào PGH vừa tạo ở B1:
	
	EXEC dbo.THEMSANPHAM_PGH @ID_PO = 11,        -- int
                         @ID_SP = 2,        -- int
                         @MABACKORDER = NULL, -- char(10)
                         @SOLUONG = 2,      -- smallint
                         @DONGIA = 300       -- int
*/
