USE QLTIKIMINI
GO



/*REF: https://www.sqlshack.com/sql-while-loop-with-simple-examples/
*/
/*Create account*/
/*Ve phia NBH*/
IF OBJECT_ID('CREATE_ACCOUNT_NBH','P') IS NOT NULL
	DROP PROC CREATE_ACCOUNT_NBH
GO
CREATE PROCEDURE CREATE_ACCOUNT_NBH 
@TENNBH NVARCHAR(50), 
@USERNAMENBH CHAR(20), 
@PASSNBH CHAR(20),
@VAT CHAR(15),
@SDTNBH CHAR(11),
@EMAILNBH CHAR(30),
@MDK_KINHDOANH CHAR(15),
@TENCUAHANG NVARCHAR(50),
@DCHICUAHANG NVARCHAR(100),
@MA_DANHMUCNGANH INT,
@MA_MHVH CHAR(10)
AS
BEGIN
		DECLARE @ID_NBH INT;
		DECLARE @COUNT INT = (SELECT COUNT(ID_KH) FROM KHACHHANG)
		DECLARE @ROWOFNBH INT =  (SELECT COUNT(ID_NBH) FROM NHABANHANG)
		WHILE(@COUNT > 0)
		BEGIN
			IF(EXISTS (SELECT * FROM KHACHHANG WHERE KHACHHANG.USERNAME_KH  =  @USERNAMENBH))
			BEGIN
				PRINT N'Username của NBH trùng với username của KH. Vui lòng nhập lại'
				RETURN;
			END
			SET @COUNT = @COUNT - 1;
		END
		SET @ID_NBH = @ROWOFNBH + 1;
		INSERT INTO NHABANHANG 
		VALUES(@ID_NBH, @TENNBH, @USERNAMENBH, @PASSNBH, @VAT, @SDTNBH, @EMAILNBH, @MDK_KINHDOANH, @TENCUAHANG, @DCHICUAHANG, @MA_DANHMUCNGANH, @MA_MHVH)
	END
GO 


EXEC CREATE_ACCOUNT_NBH N'Trúc','meomun','123456789','12DEFS','023456789','changpham1026@gmail.com','EGHJSKA27','FLOWER SHOP','NOT NULL',NULL,NULL

/*Về phía khách hàng: ở dưới*/
IF OBJECT_ID('CREATE_ACCOUNT_KH','P') IS NOT NULL
	DROP PROC CREATE_ACCOUNT_KH
GO
CREATE PROCEDURE CREATE_ACCOUNT_KH
@TEN_KH NVARCHAR(50),
@DIACHI_KH NVARCHAR(100),
@GIOITINH_KH BIT = 0,
@EMAIL_KH CHAR(30),
@NGAYSINH_KH SMALLDATETIME = '2000-01-01',
@SDT_KH CHAR(11) ,
@USERNAME_KH CHAR(20),
@PASS_KH CHAR(20),
@MA_HTTT CHAR(10) = 'HTTT001'
AS
BEGIN
		DECLARE @ID_KH INT;
		DECLARE @COUNT INT = (SELECT COUNT(ID_NBH) FROM NHABANHANG)
		DECLARE @ROWOFKH INT =  (SELECT COUNT(ID_KH) FROM KHACHHANG)
		WHILE(@COUNT > 0)
		BEGIN
			IF(EXISTS (SELECT * FROM NHABANHANG WHERE NHABANHANG.USERNAMENBH =  @USERNAME_KH))
			BEGIN
				PRINT N'Username của KHÁCH HÀNG trùng với username của NBH. Vui lòng nhập lại'
				RETURN;
			END
			SET @COUNT = @COUNT - 1;
		END
		SET @ID_KH = @ROWOFKH + 1;
		INSERT INTO KHACHHANG
		VALUES(@ID_KH, @TEN_KH, @DIACHI_KH, @GIOITINH_KH, @EMAIL_KH, @NGAYSINH_KH, @SDT_KH, 
		@USERNAME_KH, @PASS_KH,0,@MA_HTTT)
END
GO

/*Giao tác thể hiện chức năng đăng nhập vào hệ thống*/
/*Về phía NBH*/
IF OBJECT_ID('USP_LOGIN_NBH','P') IS NOT NULL
	DROP PROC USP_LOGIN_NBH
GO
CREATE PROC USP_LOGIN_NBH
@USERNAMENBH CHAR(20), 
@PASSNBH CHAR(20)
AS
BEGIN TRANSACTION
	BEGIN TRY
		IF NOT EXISTS (SELECT * FROM NHABANHANG WHERE NHABANHANG.USERNAMENBH = @USERNAMENBH)
		BEGIN
			PRINT N'Username không tồn tại';
			ROLLBACK TRANSACTION;
			RETURN;
		END
		IF NOT EXISTS (SELECT * FROM NHABANHANG WHERE NHABANHANG.USERNAMENBH = @USERNAMENBH AND NHABANHANG.PASSNBH = @PASSNBH)
		BEGIN
			PRINT N'Sai mật khẩu';
			ROLLBACK TRANSACTION;
			RETURN;
		END
	END TRY
	BEGIN CATCH
		PRINT N'Lỗi đăng nhập'
		ROLLBACK TRANSACTION;
	END CATCH
	PRINT N'Đăng nhập thành công'
COMMIT TRANSACTION

EXEC USP_LOGIN_NBH 'Teri18','k58WMpuvBsrU'

/*Về phía KH*/
IF OBJECT_ID('USP_LOGIN_KH','P') IS NOT NULL
	DROP PROC USP_LOGIN_KH
GO
CREATE PROC USP_LOGIN_KH
@USERNAMEKH CHAR(20), 
@PASSKH CHAR(20)
AS
BEGIN TRANSACTION
	BEGIN TRY
		IF NOT EXISTS (SELECT * FROM KHACHHANG WHERE KHACHHANG.USERNAME_KH = @USERNAMEKH)
		BEGIN
			PRINT N'Username không tồn tại';
			ROLLBACK TRANSACTION;
			RETURN;
		END
		IF NOT EXISTS (SELECT * FROM KHACHHANG WHERE KHACHHANG.USERNAME_KH = @USERNAMEKH AND KHACHHANG.PASS_KH = @PASSKH)
		BEGIN
			PRINT N'Sai mật khẩu';
			ROLLBACK TRANSACTION;
			RETURN;
		END
	END TRY
	BEGIN CATCH
		PRINT N'Lỗi đăng nhập'
		ROLLBACK TRANSACTION;
	END CATCH
	PRINT N'Đăng nhập thành công'
COMMIT TRANSACTION

EXEC USP_LOGIN_KH 'Chanda735','Kentucky'


/*Hàm cấp tài khoản Mã nhân viên tự động*/
IF OBJECT_ID('GENERATE_USERNAMENV') IS NOT NULL
	DROP FUNCTION dbo.GENERATE_USERNAMENV
GO
CREATE FUNCTION GENERATE_USERNAMENV ()
RETURNS CHAR(20)
AS
BEGIN
	DECLARE @USERNAMECHONV CHAR(20);
	DECLARE @INDEX INT = 2;
	SET @USERNAMECHONV = 'NV00000001';
	WHILE(EXISTS (SELECT NHANVIEN.USERNAME_NV FROM NHANVIEN WHERE NHANVIEN.USERNAME_NV = @USERNAMECHONV))
		BEGIN
			IF (@INDEX < 10)
			BEGIN
				SET @USERNAMECHONV = 'HD0000000' + CONVERT(CHAR(5),@INDEX)
			END
			ELSE IF (@INDEX >= 10 AND @INDEX < 100)
			BEGIN
				SET @USERNAMECHONV = 'HD000000' + CONVERT(CHAR(5),@INDEX)
			END
			ELSE IF (@INDEX >= 100 AND @INDEX < 1000)
			BEGIN
				SET @USERNAMECHONV = 'HD00000' + CONVERT(CHAR(5),@INDEX)
			END
			ELSE IF (@INDEX >= 1000 AND @INDEX < 10000)
			BEGIN
				SET @USERNAMECHONV = 'HD0000' + CONVERT(CHAR(5),@INDEX)
			END
			ELSE IF (@INDEX >= 10000 AND @INDEX < 100000)
			BEGIN
				SET @USERNAMECHONV = 'HD000' + CONVERT(CHAR(5),@INDEX)
			END
			SET @INDEX = @INDEX + 1
		END
	RETURN @USERNAMECHONV
END
GO
DECLARE @USERNAMECHONV CHAR(20)
SET @USERNAMECHONV = (SELECT dbo.GENERATE_USERNAMENV () AS USNNV)
PRINT @USERNAMECHONV
/*Hàm cấp psw Mã nhân viên tự động*/
IF OBJECT_ID('GENERATE_PSWNV') IS NOT NULL
	DROP FUNCTION dbo.GENERATE_PSWNV
GO
CREATE FUNCTION GENERATE_PSWNV ()
RETURNS CHAR(20)
AS
BEGIN
	DECLARE @PASSWORDNV CHAR(20);
	DECLARE @INDEX INT = 2;
	SET @PASSWORDNV = 'PASS00000001';
	WHILE(EXISTS (SELECT NHANVIEN.PASS_NV FROM NHANVIEN WHERE NHANVIEN.PASS_NV = @PASSWORDNV))
		BEGIN
			IF (@INDEX < 10)
			BEGIN
				SET @PASSWORDNV = 'PASS0000000' + CONVERT(CHAR(5),@INDEX)
			END
			ELSE IF (@INDEX >= 10 AND @INDEX < 100)
			BEGIN
				SET @PASSWORDNV = 'PASS000000' + CONVERT(CHAR(5),@INDEX)
			END
			ELSE IF (@INDEX >= 100 AND @INDEX < 1000)
			BEGIN
				SET @PASSWORDNV = 'PASS00000' + CONVERT(CHAR(5),@INDEX)
			END
			ELSE IF (@INDEX >= 1000 AND @INDEX < 10000)
			BEGIN
				SET @PASSWORDNV = 'PASS0000' + CONVERT(CHAR(5),@INDEX)
			END
			ELSE IF (@INDEX >= 10000 AND @INDEX < 100000)
			BEGIN
				SET @PASSWORDNV = 'PASS000' + CONVERT(CHAR(5),@INDEX)
			END
			SET @INDEX = @INDEX + 1
		END
	RETURN @PASSWORDNV
END
GO
DECLARE @PASSCHONV CHAR(20)
SET @PASSCHONV = (SELECT dbo.GENERATE_PSWNV() AS PSWNV)
PRINT @PASSCHONV

/*Kịch bản 1*/

/*B1: Khách hàng đăng ký tài khoản --> có ở trên*/



EXEC CREATE_ACCOUNT_KH N'Trang',N'23A Berkeley',1,'changpham1026@gmail.com','2000-10-26','0707653589','trangcutephomai','123456'
SELECT * FROM KHACHHANG

/*B2: Khách hàng đăng nhập vào hệ thống ---> có ở trên*/
EXEC USP_LOGIN_KH 'trangcutephomai','123456'


/*B3a: Khách hàng tìm sản phẩm theo danh mục*/
IF OBJECT_ID('KICHBAN1_GIAKHUYENMAIGIAMDAN','P') IS NOT NULL
	DROP PROC KICHBAN1_GIAKHUYENMAIGIAMDAN
GO

CREATE PROCEDURE KICHBAN1_GIAKHUYENMAIGIAMDAN
@DANHMUC INT
AS
BEGIN
	PRINT N'Danh sách các sản phẩm thuộc danh mục ' + CONVERT(VARCHAR,@DANHMUC) ;
	IF (@DANHMUC IS NULL)
	BEGIN
		SELECT SANPHAM.ID_SP, SANPHAM.TEN_SPHAM, SANPHAM.GIANIEMYET, SANPHAM.GIAKHUYENMAI, SANPHAM.THOIGIANKM, SANPHAM.HANSUDUNGSP,
		SANPHAM.MOTACHITIET_SP, SANPHAM.GHICHUSPHAM, DANHMUCNGANH.TEN_DMN, THUONGHIEU.TENTH
		FROM SANPHAM, DANHMUCNGANH, THUONGHIEU
		WHERE DANHMUCNGANH.ID_DMN = SANPHAM.ID_DMN AND SANPHAM.ID_TH = THUONGHIEU.ID_TH
		ORDER BY SANPHAM.TEN_SPHAM ASC
	END
	/*Kiem tra neu k co san pham nao phu hop voi dmnganh thi bao loi */
	ELSE IF(NOT EXISTS (SELECT * FROM SANPHAM WHERE SANPHAM.ID_DMN = @DANHMUC))
	BEGIN
		PRINT N'Không có sản phẩm tương ứng'
		RETURN;
	END
	ELSE
		SELECT SANPHAM.ID_SP, SANPHAM.TEN_SPHAM, SANPHAM.GIANIEMYET, SANPHAM.GIAKHUYENMAI, SANPHAM.THOIGIANKM, SANPHAM.HANSUDUNGSP,
		SANPHAM.MOTACHITIET_SP, SANPHAM.GHICHUSPHAM, DANHMUCNGANH.TEN_DMN, THUONGHIEU.TENTH
		FROM SANPHAM, DANHMUCNGANH, THUONGHIEU
		WHERE DANHMUCNGANH.ID_DMN = @DANHMUC AND
		SANPHAM.ID_DMN = @DANHMUC AND THUONGHIEU.ID_TH = SANPHAM.ID_TH
		ORDER BY SANPHAM.TEN_SPHAM ASC
END

EXEC KICHBAN1_GIAKHUYENMAIGIAMDAN 107

/*B3B: Khách hàng tìm sản phẩm theo: % giá được khuyến mãi --> hiển thị ra sản phẩm tương ứng*/
IF OBJECT_ID('KICHBAN1_RATEGIAMGIA','P') IS NOT NULL
	DROP PROC KICHBAN1_RATEGIAMGIA
GO
CREATE PROCEDURE KICHBAN1_RATEGIAMGIA
@TILEGIAMGIA SMALLINT = 0
AS
BEGIN
	DECLARE @MAXID INT, @MINID INT
	DECLARE @GIATIEN FLOAT, @GIAKHUYENMAI FLOAT, @FLAG BIT = 1
	/*Tim chi so lon nhat va be nhat*/
	SELECT @MINID = MIN(VOUCHER_D.ID_VOUCHER), @MAXID = MAX(VOUCHER_D.ID_VOUCHER)
	FROM VOUCHER_D
	PRINT N'Danh sách voucher có tỉ lệ khuyến mãi là ' + CONVERT(VARCHAR,@TILEGIAMGIA) + ' %'
	WHILE(@MINID > 0 AND @MINID <= @MAXID )
	BEGIN
		SET @GIATIEN = (SELECT VOUCHER_D.GIATIEN FROM VOUCHER_D WHERE VOUCHER_D.ID_VOUCHER = @MINID AND VOUCHER_D.GIAKHUYENMAI <> 0)
		SET @GIAKHUYENMAI= (SELECT VOUCHER_D.GIAKHUYENMAI FROM VOUCHER_D WHERE VOUCHER_D.ID_VOUCHER = @MINID AND VOUCHER_D.GIAKHUYENMAI <> 0)
		DECLARE @RATEGIAMGIATINHDUOC INT
		SET @RATEGIAMGIATINHDUOC = (100 / @GIATIEN) * (@GIATIEN - @GIAKHUYENMAI)
		IF (@RATEGIAMGIATINHDUOC = @TILEGIAMGIA)
		BEGIN 
			/*Hiển thị danh sách voucher*/
			SELECT TENVOUCHER, GIATIEN, GIAKHUYENMAI, DKSUDUNG, DACDIEMNOIBAT, THOIHANSUDUNG
			FROM VOUCHER_D
			WHERE VOUCHER_D.ID_VOUCHER = @MINID
			SET @FLAG = 0
		END
		SET @MINID = @MINID + 1;
	END
	IF(@FLAG = 1)
	BEGIN
		PRINT N'Không có voucher nào thỏa yêu cầu'
		RETURN;
	END
END
EXEC KICHBAN1_RATEGIAMGIA 40
/*3 giá tiền: 40 - 50 - 80*/
/*B4: Dang ky mua 1 voucher*/
IF OBJECT_ID('KICHBAN1_MUAVOUCHER','P') IS NOT NULL
	DROP PROC KICHBAN1_MUAVOUCHER
GO
CREATE PROCEDURE KICHBAN1_MUAVOUCHER
@MAKH INT, @MAVOUCHER INT = NULL, @SOLUONG INT = 1, @DTHOAI CHAR(11)
AS
BEGIN
	IF(NOT EXISTS (SELECT * FROM VOUCHER_D WHERE VOUCHER_D.ID_VOUCHER = @MAVOUCHER))
	BEGIN
		PRINT N'Không tồn tại voucher này'
		RETURN;
	END
	IF @SOLUONG <= 0
	BEGIN
		PRINT N'Vui lòng nhập số lượng >=1'
		RETURN;
	END
	--PRINT N'Thông tin chi tiết voucher'
	SELECT * FROM VOUCHER_D WHERE VOUCHER_D.ID_VOUCHER = @MAVOUCHER
	INSERT INTO CHITIETMUAVOUCHER VALUES(@MAKH, @MAVOUCHER,@SOLUONG,@DTHOAI)
	PRINT N'Bạn đã mua voucher thành công!'
	--PRINT N'Thông tin chi tiết sau khi mua voucher'
	SELECT VOUCHER_D.*, KHACHHANG.TEN_KH
	FROM VOUCHER_D, KHACHHANG, CHITIETMUAVOUCHER
	WHERE VOUCHER_D.ID_VOUCHER = CHITIETMUAVOUCHER.ID_VOUCHER AND CHITIETMUAVOUCHER.ID_KH = KHACHHANG.ID_KH
	AND KHACHHANG.ID_KH = @MAKH AND VOUCHER_D.ID_VOUCHER = @MAVOUCHER
END

EXEC KICHBAN1_MUAVOUCHER 990,25,2,'0707653589'
DELETE FROM CHITIETMUAVOUCHER WHERE DIENTHOAINHANMA = '0707653589'
select * from CHITIETMUAVOUCHER

