/** CREATE CSDL */
-- TẠO CSDL CHO HỆ THỐNG TIKIMINI
USE master 
GO
IF DB_ID('QLTIKIMINI') IS NOT NULL
	DROP DATABASE QLTIKIMINI
GO
CREATE DATABASE QLTIKIMINI

USE QLTIKIMINI
GO


CREATE TABLE DONHANG
(
	ID_DH INT NOT NULL,
	--MA_DONHANG CHAR(10) NOT NULL,
	THOIGIANDAT SMALLDATETIME NOT NULL,
	TRANGTHAI TINYINT NOT NULL,
	THOIGIANGIAO SMALLDATETIME DEFAULT NULL,
	THOIGIANXN SMALLDATETIME DEFAULT NULL,
	CHECK (THOIGIANGIAO >= THOIGIANDAT),
	CHECK (THOIGIANXN >= THOIGIANGIAO),
	DIACHIGIAOHANG NVARCHAR(100) DEFAULT NULL,
	TONGCONG INT DEFAULT 0,
	ID_COUPONGIAMGIA INT,
	MA_HTGH CHAR(10),
	MA_HTTT CHAR(10),
	ID_KH INT,
	ID_NV INT,
	ID_PO INT

	CONSTRAINT PK_MADH -- dat ten khoa chinh
	PRIMARY KEY (ID_DH)
);

CREATE TABLE HUYDONHANG
(
	ID_DH INT NOT NULL,
	LYDOHUY NVARCHAR(50) NOT NULL,
	GHICHU NVARCHAR(50) NOT NULL

	CONSTRAINT PK_MADH_HDH -- dat ten khoa chinh
	PRIMARY KEY (ID_DH)

	FOREIGN KEY (ID_DH) REFERENCES DONHANG(ID_DH),
);

CREATE TABLE HOADON
(
	ID_HOADON INT NOT NULL,
	TENCONGTY NVARCHAR(50)  NOT NULL,
	MASOTHUE CHAR(10) NOT NULL,
	DIACHICTY NVARCHAR(100) NOT NULL,
	ID_DH INT

	CONSTRAINT PK_MAHD -- dat ten khoa chinh
	PRIMARY KEY (ID_HOADON),

	FOREIGN KEY (ID_DH) REFERENCES DONHANG(ID_DH)
);

CREATE TABLE COUPONGIAMGIA
(
	ID_COUPONGIAMGIA INT NOT NULL,
	TEN_GIAMGIA NVARCHAR(100) UNIQUE NOT NULL,
	RATE TINYINT NOT NULL,
	MOTA NVARCHAR(100) NOT NULL,
	HANSUDUNG_CO SMALLDATETIME NOT NULL

	CONSTRAINT PK_CPGIAMGIA -- dat ten khoa chinh
	PRIMARY KEY (ID_COUPONGIAMGIA)

)

CREATE TABLE HINHTHUCGIAOHANG
(
	MA_HTGH CHAR(10) NOT NULL,
	
	TEN_HTGH NVARCHAR(50)  NOT NULL,
	DK_HTGH NVARCHAR(50) NOT NULL,
	PHIGH INT NOT NULL,
	THOIGIANDUKIEN NVARCHAR(30) DEFAULT NULL

	CONSTRAINT PK_HTGH -- dat ten khoa chinh
	PRIMARY KEY (MA_HTGH)

);

CREATE TABLE HINHTHUCTHANHTOAN
(
	MA_HTTT CHAR(10) NOT NULL,
	
	TEN_HTTT NVARCHAR(50) NOT NULL,
	GHICHU NVARCHAR(50) NOT NULL

	CONSTRAINT PK_HTTT -- dat ten khoa chinh
	PRIMARY KEY (MA_HTTT)

);

CREATE TABLE QUATANGSINHNHAT
(
	ID_QUATANGSN INT NOT NULL,
	PHIQUATANG INT NOT NULL,
	THONGDIEP NVARCHAR(50) NOT NULL,
	TENNGUOINHAN NVARCHAR(50) NOT NULL,
	DIACHIGIAOQUA NVARCHAR(50) NOT NULL,
	ID_DH INT

	CONSTRAINT PK_QTSN -- dat ten khoa chinh
	PRIMARY KEY (ID_QUATANGSN)

	--Khoas nai
	FOREIGN KEY (ID_DH) REFERENCES DONHANG(ID_DH),
);

CREATE TABLE KHACHHANG
(
	ID_KH INT NOT NULL,
	--MA_KH CHAR(10) NOT NULL,
	TEN_KH NVARCHAR(50) NOT NULL,
	DIACHI_KH NVARCHAR(100) NOT NULL,
	GIOITINH_KH BIT NOT NULL,
	EMAIL_KH CHAR(30) NOT NULL,
	NGAYSINH_KH SMALLDATETIME NOT NULL,
	SDT_KH CHAR(11) NOT NULL,
	USERNAME_KH CHAR(20) NOT NULL UNIQUE,
	PASS_KH CHAR(20) NOT NULL,
	TIKIXU INT DEFAULT 0,
	MA_HTTT CHAR(10)

	CONSTRAINT PK_KH -- dat ten khoa chinh
	PRIMARY KEY (ID_KH)

	--Khoas nai
	FOREIGN KEY (MA_HTTT) REFERENCES HINHTHUCTHANHTOAN(MA_HTTT),
);

CREATE TABLE DICHVUBOOKCARE
(
	MA_IDVBOOKCARE CHAR(10) NOT NULL,
	TEN_IDVBOOKCARE NVARCHAR(40) NOT NULL,
	GIA_IDVBOOKCARE INT NOT NULL,
	SL_IDVBOOKCARE TINYINT NOT NULL
	CHECK (SL_IDVBOOKCARE > 0)

	CONSTRAINT PK_DVBKCARE -- dat ten khoa chinh
	PRIMARY KEY (MA_IDVBOOKCARE)
);

CREATE TABLE DK_DICHVUBOOKCARE
(
	ID_KH INT NOT NULL,
	MA_IDVBOOKCARE CHAR(10) NOT NULL,
	SLDADUNG INT NOT NULL,
	CHECK (SLDADUNG >= 0),
	SLCONLAI INT NOT NULL,
	CHECK (SLCONLAI >= 0),

	CONSTRAINT PK_DANGKYDVBKCARE -- dat ten khoa chinh
	PRIMARY KEY (ID_KH, MA_IDVBOOKCARE),

	--Khoas nai
	FOREIGN KEY (ID_KH) REFERENCES KHACHHANG(ID_KH),
	FOREIGN KEY (MA_IDVBOOKCARE) REFERENCES DICHVUBOOKCARE(MA_IDVBOOKCARE)
);

CREATE TABLE TIKICARD
(
	ID_TIKICARD INT NOT NULL,
	HANSUDUNG SMALLDATETIME NOT NULL,
	PT_HOANTIENTC TINYINT NOT NULL,
	--DEFAULT 0 FOR PT_HOANTIENTC,
	QUATANGTC NVARCHAR(50),
	ID_KH INT

	CONSTRAINT PK_TKICARD_KH
	PRIMARY KEY (ID_TIKICARD)
	--Khoas nai
	FOREIGN KEY (ID_KH) REFERENCES KHACHHANG(ID_KH)
);

CREATE TABLE NHANVIEN
(
	ID_NV INT NOT NULL,
	--MA_NV CHAR(10) NOT NULL,
	TENNV CHAR(50) NOT NULL,
	USERNAME_NV CHAR(20) UNIQUE NOT NULL,
	PASS_NV CHAR(20) NOT NULL,
	TYPENV TINYINT NOT NULL,
	DCHINV NVARCHAR(100) NOT NULL,
	SDTNV CHAR(11) NOT NULL,
	EMAILNV CHAR(50) NOT NULL,
	GIOITINHNV BIT NOT NULL,
	CMNDNV CHAR(12) UNIQUE NOT NULL,
	LUONGNV REAL NOT NULL,
	CHECK (LUONGNV > 0),
	QUANLY INT

	CONSTRAINT PK_NV
	PRIMARY KEY (ID_NV)

	--Khoas nai
	FOREIGN KEY (ID_NV) REFERENCES NHANVIEN(ID_NV),
);

CREATE TABLE KHOTIKI
(
	MAKHO CHAR(10) NOT NULL,
	TENKHO CHAR(4) NOT NULL,
	DCHIKHO NVARCHAR(250) NOT NULL,
	LOAIKHO NVARCHAR(30) NOT NULL,
	FLAG_SPAPDUNG NVARCHAR(50) NOT NULL,
	SDTKHO CHAR(11) NOT NULL,
	FLAG_THOIGIANGH NVARCHAR(50) NOT NULL,
	ID_NV INT

	CONSTRAINT PK_KHO
	PRIMARY KEY (MAKHO)

	--Khoas nai
	FOREIGN KEY (ID_NV) REFERENCES NHANVIEN(ID_NV),
);

CREATE TABLE NHABANHANG
(
	ID_NBH INT NOT NULL,
	--MANBH CHAR(10) NOT NULL,
	TENNBH NVARCHAR(50) NOT NULL,
	USERNAMENBH CHAR(20) UNIQUE NOT NULL,
	PASSNBH CHAR(20) NOT NULL,
	VAT CHAR(15) NOT NULL,
	SDTNBH CHAR(11) NOT NULL,
	EMAILNBH CHAR(30) NOT NULL,
	MDK_KINHDOANH CHAR(15) UNIQUE NOT NULL,
	TENCUAHANG NVARCHAR(50) NOT NULL,
	DCHICUAHANG NVARCHAR(100) NOT NULL,
	ID_DMN INT,
	MA_MHVH CHAR(10)

	CONSTRAINT PK_NBH
	PRIMARY KEY (ID_NBH)

	--- THEM KHOA NGOAI
);


CREATE TABLE TAIKHOANNGANHANG
(
	MATAIKHOAN CHAR(10) NOT NULL,
	TENCHUTK NVARCHAR(50) NOT NULL,
	STK CHAR(20) NOT NULL,
	NGANHANGDK NVARCHAR(50) NOT NULL,
	CHINHANH NVARCHAR(30) NOT NULL,
	ID_NBH INT

	CONSTRAINT PK_TAIKHOANNH
	PRIMARY KEY (MATAIKHOAN)

	FOREIGN KEY (ID_NBH) REFERENCES NHABANHANG(ID_NBH),
);

CREATE TABLE DANHMUCNGANH
(
	ID_DMN INT NOT NULL,
	TEN_DMN NVARCHAR(50) NOT NULL,
	PHANCAP INT

	CONSTRAINT PK_DMN
	PRIMARY KEY (ID_DMN)

	FOREIGN KEY (PHANCAP) REFERENCES DANHMUCNGANH(ID_DMN),
);

CREATE TABLE THUONGHIEU
(
	ID_TH INT NOT NULL,
	TENTH NVARCHAR(50) NOT NULL

	CONSTRAINT PK_THUONGHIEU
	PRIMARY KEY (ID_TH)
);

CREATE TABLE SANPHAM
(
	ID_SP INT NOT NULL,
	--MA_SPHAM CHAR(10) NOT NULL,
	TEN_SPHAM NVARCHAR(50) UNIQUE NOT NULL,
	MOTACHITIET_SP NVARCHAR(100) UNIQUE NOT NULL,
	KHOILUONG SMALLINT NOT NULL,
	CHECK (KHOILUONG > 0),
	GIANIEMYET FLOAT NOT NULL,
	GIAKHUYENMAI FLOAT NOT NULL,
	--DEFAULT 0 FOR GIAKHUYENMAI,
	CHECK (GIAKHUYENMAI <= GIANIEMYET),
	THOIGIANKM TINYINT,
	SOLUONGTONKHO INT,
	GHICHUSPHAM NVARCHAR(50) UNIQUE NOT NULL,
	HANSUDUNGSP SMALLDATETIME NOT NULL,
	NOISX NVARCHAR(50) NOT NULL,
	PHITIKITHU INT,
	CHECK (PHITIKITHU > 0),
	LOAICAUTRUCSP TINYINT NOT NULL,
	ID_TH INT,
	ID_DMN INT

	CONSTRAINT PK_SPHAM
	PRIMARY KEY (ID_SP)

	FOREIGN KEY (ID_TH) REFERENCES THUONGHIEU(ID_TH),
	FOREIGN KEY (ID_DMN) REFERENCES DANHMUCNGANH(ID_DMN)
);

CREATE TABLE DANHGIASP 
(
	ID_KH INT NOT NULL,
	ID_SP INT NOT NULL,
	BINHLUAN NVARCHAR(50) NOT NULL,
	SCORERATING TINYINT DEFAULT NULL,
	CHECK(SCORERATING >=1 AND SCORERATING <= 5),
	NGAYBINHLUAN SMALLDATETIME NOT NULL

	CONSTRAINT PK_DANHGIASP
	PRIMARY KEY (ID_KH, ID_SP)

	FOREIGN KEY (ID_KH) REFERENCES KHACHHANG(ID_KH),
	FOREIGN KEY (ID_SP) REFERENCES SANPHAM(ID_SP)
);

CREATE TABLE MSKU 
(
	ID_SP INT NOT NULL,
	MA_MSKU CHAR(10) NOT NULL

	CONSTRAINT PK_MSKU
	PRIMARY KEY (ID_SP)

	FOREIGN KEY (ID_SP) REFERENCES SANPHAM(ID_SP)
);

CREATE TABLE SSKU
(
	ID_SP INT NOT NULL,
	MA_SSKU CHAR(10) NOT NULL,
	MINCODE CHAR(15) NOT NULL

	CONSTRAINT PK_SSKU
	PRIMARY KEY (ID_SP)

	FOREIGN KEY (ID_SP) REFERENCES SANPHAM(ID_SP)
);

CREATE TABLE CHITIETDONHANG
(
	ID_DH INT NOT NULL,
	ID_SP INT NOT NULL,
	SL_SPMUA TINYINT NOT NULL,
	CHECK (SL_SPMUA > 0),
	GIA_SP INT NOT NULL

	CONSTRAINT PK_CTDHANG
	PRIMARY KEY (ID_DH, ID_SP)

	FOREIGN KEY (ID_SP) REFERENCES SANPHAM(ID_SP),
	FOREIGN KEY (ID_DH) REFERENCES DONHANG(ID_DH)
);

CREATE TABLE MOHINHVANHANH
(
	MA_MHVH CHAR(10) NOT NULL,
	TEN_MHVH NVARCHAR(50) NOT NULL,
	LOAI_MHVH TINYINT NOT NULL,
	LUUY_MHVH NVARCHAR(50) NOT NULL,
	PHI_XULYDH SMALLINT DEFAULT NULL,
	PHI_HV SMALLINT DEFAULT NULL,
	PHILAYHANG SMALLINT DEFAULT NULL

	CONSTRAINT PK_MHVH
	PRIMARY KEY (MA_MHVH)

);
CREATE TABLE THUOCTINHSP
(
	ID_THUOCTINHSP INT NOT NULL,
	TEN_THUOCTINH NVARCHAR(50) NOT NULL,
	GIATRITHUOCTINH CHAR(20) NOT NULL,
	LOAITHUOCTINH BIT NOT NULL

	/*0: COLOR, 1: SIZE */
	CONSTRAINT PK_THUOCTINH
	PRIMARY KEY (ID_THUOCTINHSP)

);

CREATE TABLE PHIEUGUIHANG
(
	ID_PO INT NOT NULL,
	MAPO CHAR(10) NOT NULL,
	TRANGTHAI TINYINT NOT NULL,
	NGAYPO SMALLDATETIME NOT NULL,
	MINCODEPGH CHAR(15) NOT NULL,
	LIENHE NVARCHAR(50) NOT NULL,
	NGAYGUIHANGDK SMALLDATETIME NOT NULL,
	LOAIHINHNHAPKHO NVARCHAR(40) NOT NULL,
	GHICHU NVARCHAR(50) NOT NULL,
	DIACHIGIAOHANG NVARCHAR(100) NOT NULL,
	TONGTIEN INT NOT NULL DEFAULT 0,
	MA_MHVH CHAR(10),
	MAKHO CHAR(10),
	ID_NBH INT

	CONSTRAINT PK_PHIEUGUIHANG
	PRIMARY KEY (ID_PO)

	FOREIGN KEY (MAKHO) REFERENCES KHOTIKI(MAKHO),
	FOREIGN KEY (ID_NBH) REFERENCES NHABANHANG(ID_NBH),
	FOREIGN KEY (MA_MHVH) REFERENCES MOHINHVANHANH(MA_MHVH)
);

CREATE TABLE CHITIETPHIEUGUIHANG
(
	ID_PO INT NOT NULL,
	ID_SP INT NOT NULL,
	MABACKORDER CHAR(10) DEFAULT NULL,
	SOLUONG SMALLINT NOT NULL,
	CHECK(SOLUONG > 0),
	/*Do so luong nhap co the lon*/
	DONGIA INT NOT NULL

	CONSTRAINT PK_CTPGH
	PRIMARY KEY (ID_PO, ID_SP)

	FOREIGN KEY (ID_SP) REFERENCES SANPHAM(ID_SP),
	FOREIGN KEY (ID_PO) REFERENCES PHIEUGUIHANG(ID_PO)

);

CREATE TABLE SSKUCOTHUOCTINH
(
	ID_THUOCTINHSP INT NOT NULL,
	ID_SP INT NOT NULL

	/*0: COLOR, 1: SIZE, 2: ALL*/
	CONSTRAINT PK_SSKUCOTT
	PRIMARY KEY (ID_THUOCTINHSP, ID_SP)

	FOREIGN KEY (ID_THUOCTINHSP) REFERENCES THUOCTINHSP(ID_THUOCTINHSP),
	
	--- Them khoa ngoai cho MA_SSKU
	FOREIGN KEY (ID_SP) REFERENCES SSKU(ID_SP)
);
CREATE TABLE MSKUCOTHUOCTINH
(
	ID_THUOCTINHSP INT NOT NULL,
	ID_SP INT NOT NULL

	/*0: COLOR, 1: SIZE, 2: ALL*/
	CONSTRAINT PK_MSKUCOTT
	PRIMARY KEY (ID_THUOCTINHSP, ID_SP)

	FOREIGN KEY (ID_THUOCTINHSP) REFERENCES THUOCTINHSP(ID_THUOCTINHSP),
	--- Them khoa ngoai cho MA_MSKU
	FOREIGN KEY (ID_SP) REFERENCES MSKU(ID_SP)
);
CREATE TABLE VOUCHER_D
(
	ID_VOUCHER INT NOT NULL,
	TENVOUCHER NVARCHAR(50) NOT NULL,
	GIATIEN FLOAT NOT NULL,
	GIAKHUYENMAI FLOAT NOT NULL,
	CHECK (GIATIEN >= GIAKHUYENMAI),
	DKSUDUNG NVARCHAR(50) NOT NULL,
	DACDIEMNOIBAT NVARCHAR(100) NOT NULL,
	THOIHANSUDUNG SMALLDATETIME NOT NULL,
	ID_DMN INT

	CONSTRAINT PK_VOUCHERD
	PRIMARY KEY (ID_VOUCHER)

	FOREIGN KEY (ID_DMN) REFERENCES DANHMUCNGANH(ID_DMN)
);
CREATE TABLE DIACHISUDUNG
(
	ID_VOUCHER INT NOT NULL,
	SONHA NVARCHAR(30) NOT NULL,
	DUONG NVARCHAR(50) NOT NULL,
	QUAN NVARCHAR(50) NOT NULL,
	THANHPHO NVARCHAR(50) NOT NULL

	CONSTRAINT PK_DCVOUCHER
	PRIMARY KEY (ID_VOUCHER)

	FOREIGN KEY (ID_VOUCHER) REFERENCES VOUCHER_D(ID_VOUCHER)
);
CREATE TABLE DANGBANVOUCHER
(
	ID_NBH INT NOT NULL,
	ID_VOUCHER INT NOT NULL,
	NGAYDANGBANV SMALLDATETIME NOT NULL

	CONSTRAINT PK_DBANVOUCHER
	PRIMARY KEY (ID_NBH, ID_VOUCHER)

	FOREIGN KEY (ID_VOUCHER) REFERENCES VOUCHER_D(ID_VOUCHER),
	FOREIGN KEY (ID_NBH) REFERENCES NHABANHANG(ID_NBH)
);
CREATE TABLE DANGBANSANPHAM
(
	ID_NBH INT NOT NULL,
	ID_SP INT NOT NULL,
	NGAYDANGBANSP SMALLDATETIME NOT NULL

	CONSTRAINT PK_DBANSP
	PRIMARY KEY (ID_NBH,ID_SP)

	FOREIGN KEY (ID_SP) REFERENCES SANPHAM(ID_SP),
	FOREIGN KEY (ID_NBH) REFERENCES NHABANHANG(ID_NBH)
);
CREATE TABLE CHITIETMUAVOUCHER
(
	ID_KH INT NOT NULL, 
	ID_VOUCHER INT NOT NULL,
	SOLUONG SMALLINT NOT NULL,
	CHECK (SOLUONG > 0),
	DIENTHOAINHANMA CHAR(11) NOT NULL

	CONSTRAINT PK_CTMUAVOUCHER
	PRIMARY KEY (ID_KH,ID_VOUCHER)

	FOREIGN KEY (ID_VOUCHER) REFERENCES VOUCHER_D(ID_VOUCHER),
	FOREIGN KEY (ID_KH) REFERENCES KHACHHANG(ID_KH)
);


--ADD THEM KHOA NGOAI NHUNG TABLE CHUA CO FOREIGN KEY
ALTER TABLE DONHANG
ADD
	CONSTRAINT FK_DONHANG_GIAMGIA
	FOREIGN KEY (ID_COUPONGIAMGIA)
	REFERENCES COUPONGIAMGIA
ALTER TABLE DONHANG
ADD
	CONSTRAINT FK_DONHANG_HTTT
	FOREIGN KEY (MA_HTTT)
	REFERENCES HINHTHUCTHANHTOAN
ALTER TABLE DONHANG
ADD
	CONSTRAINT FK_DONHANG_KHACHHANG
	FOREIGN KEY (ID_KH)
	REFERENCES KHACHHANG
ALTER TABLE DONHANG
ADD
	CONSTRAINT FK_DONHANG_PTGH
	FOREIGN KEY (MA_HTGH)
	REFERENCES HINHTHUCGIAOHANG
ALTER TABLE DONHANG
ADD
	CONSTRAINT FK_DONHANG_NHANVIENQUANLY
	FOREIGN KEY (ID_NV)
	REFERENCES NHANVIEN
ALTER TABLE DONHANG
ADD
	CONSTRAINT FK_DONHANG_PGH
	FOREIGN KEY (ID_PO)
	REFERENCES PHIEUGUIHANG
ALTER TABLE NHABANHANG
ADD
	CONSTRAINT FK_NBH_DMN
	FOREIGN KEY (ID_DMN)
	REFERENCES DANHMUCNGANH
ALTER TABLE NHABANHANG
ADD
	CONSTRAINT FK_NBH_MHVH
	FOREIGN KEY (MA_MHVH)
	REFERENCES MOHINHVANHANH

